electron/asar

- lib/disk.js
- lib/header.js
- package.json
As follow-up to https://github.com/atom/asar/issues/16
> drop chromium-pickle dependency. implement reading / writing asar archives in pure JS

- package.json
Stop `npm` crying... (by using a SPDX license ID in package.json)
~~```npm WARN package.json asar@0.9.1 No license field.```~~
> Update package.json - refer to license by SPDX license ID

- src/asar.coffee
Hi Cheng, haven't worked on (or with asar) for quite some time. But I still have a grunt and a gulp plugin for it on npm which need to be updated *badly*.
This is just another method to create an archive. This is helpful for grunt and gulp, when some other code already did the globbing.
The code didn't change that much, as GitHub makes it seem. Most lines have just one level less indentation.
> Add new method `createPackageFromFiles` to asar module

- CHANGELOG.md
- package.json
Addresses insecure dependency warnings related to https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service
> Upgrade to minimatch@3.0.3

- bin/asar
In this patch, help information is outputted when an undefined command is used. The motivation for this change is that I performed the following command `asar pac my-app app.asar`, but nothing happened due to the typo. However, there was no feedback that indicated that something went wrong. Therefore, in this patch an undefined command will have the following output:
```
$ ./asar pac                                             
asar: 'pac' is not an asar command. See 'asar --help'.
```
The error message is inspired by Git, e.g. when an undefined command is used in Git, it outputs the following.
```
$ git abd
git: 'abc' is not a git command. See 'git --help'.
```
What are your thoughts on this? I am looking forward to receiving feedback when applicable :grimacing:
> Output help information when undefined command is used

- .gitignore
- .npmignore
- .travis.yml
- lib/asar.js
- lib/crawlfs.js
- lib/disk.js
- lib/filesystem.js
- lib/snapshot.js
- package.json
- test/api-spec.js
- test/cli-spec.js
- test/util/compareDirectories.js
- test/util/compareFiles.js
Hello!
I'm building an Electron app and I needed to work with asar packages in it. I then ran in two problems.
First, the official `asar` package didn't work on electron (and the existing `original-fs-asar` uses old code and it does not look like it is maintained).
Second, as I was modifying asar packages, I had problems with the cache mechanism used by `asar`, which often ended up using the header of an asar to read a file in another asar, resulting in output from another file than the one I was reading (wrong offsets).
So, this pull request solves both these issues, making `asar` compatible with electron (of course while still being compatible with node), and adding two methodes to remove the cache.
I'd love to see those features merged into the official `asar`, as I'm sure they could …
> Making asar compatible with electron + adding functions to remove cache

- lib/disk.js
This is a fix for https://github.com/electron/asar/issues/139 which is due to `writeFileListToStream` encountering a large enough span of `unpack` files which in turn causes the function to recurse to the point that it exceeds the maximum call stack size.  The fix eats a span of `unpack` files without recursion, but continues in the non-`unpack` case in the same manner as before.
> Fix #139: Maximum call stack size exceeded with unpack.

- bin/asar.js
- lib/asar.js
- lib/filesystem.js
- test/api-spec.js
- test/cli-spec.js
- test/expected/extractthis-filelist-with-option.txt
This pull request adds `--is-pack` option to `list` command to display pack or unpack of each files in the asar. 
Because of I would like to grasp quickly and simply whole of .asar and .asar.unpack.
That output is below, this is simple.
```sh
% ./bin/asar.js list --is-pack ./app.asar                                                                                                                                     
unpack : /x1
unpack : /x1/test
pack   : /x2
```
I hope this patch will be merged.
Best regards.
> Proposal: Add is-pack option to "list" command

- lib/asar.js
make createPackageFromFiles works without providing any options or metadata
calling like
`asar.createPackageFromFiles(toPath, fileName, paths, null, null, console.log)`
was not allowed.
> make createPackageFromFiles works

- .travis.yml
- appveyor.yml
Node 4 no longer receives updates, and Node 10 has started LTS support.
> Test against supported LTS Node versions

- lib/asar.js
- test/api-spec.js
- test/cli-spec.js
- Candidate fix for the regression introduced in commit #154. 
- Added path normalization to the arguments of createPackageFromFiles.
- Added unit tests which would otherwise fail if the paths are not normalized.
- This is my first pull request ever on GitHub, please be gentle :)
> fix: Normalized filepaths in createPackageFromFiles

- lib/filesystem.js
Ref #160 - removes the now-unused `stat` parameter from `insertLink()`.
> chore: remove unused insertLink() `stat` arg

- .circleci/config.yml
- .releaserc.json
- README.md
- package-lock.json
- package.json
I think this is all I have to do, code-wise?
> chore: add CFA support

- README.md
- appveyor.yml
- lib/asar.js
- lib/crawlfs.js
- lib/disk.js
- lib/filesystem.js
- lib/wrapped-fs.js
- package-lock.json
- package.json
- test/api-spec.js
- test/cli-spec.js
- test/util/compareDirectories.js
- test/util/compareFiles.js
BREAKING CHANGE: drop support for versions of Node which are EOL'd as of 2019-04-30.
The commit messages should give a pretty clear idea of what happened in this branch.
> feat: drop support for Node < 8

- lib/wrapped-fs.js
Discovered this bug when trying to upgrade Electron Packager. The `resolve` module never completes when `fs.readFile` is monkeypatched.
> fix: don't monkeypatch fs with promisified versions

- lib/asar.js
> chore: remove unnecessary arguments

- test/api-spec.js
glob default sort result by function `localCompare`. Multibyte characters  path test case will failed when 
the system language is Chinese, so when run this case use nosort?
> chore: multibyte characters path case use nosort

- .circleci/config.yml
- lib/asar.js
- lib/filesystem.js
- lib/wrapped-fs.js
- package-lock.json
- package.json
- test/api-spec.js
BREAKING CHANGE: Drops support for Node < 10.12.0
This allows us to drop two direct dependencies (`cuint` and `mkdirp`), plus I found a way to drop a third (`tmp-promise`) that was unrelated to the Node version change.
Also uses `stream.pipeline` (added in Node 10) which simplifies how `Filesystem.prototype.insertFile` is implemented.
> feat: require Node 10.12.0

- README.md
- bin/asar.js
This is a variation on the [version checking code in the Electron Packager CLI](https://github.com/electron/electron-packager/blob/4081666b32ba5525b84491123344e9908a9cb21d/bin/electron-packager.js#L5-L12).
Also mention the Node version requirement in the README.
Fixes #192
> fix: enforce Node version constraint for the CLI

- bin/asar.js
- package-lock.json
- package.json
- test/cli-spec.js
build(deps): upgrade commander to ^5.0.0
Fixes #186.
> fix: correctly parse arguments for list --is-pack

- lib/index.d.ts
- test/index.test-d.ts
According to [lib/filesystem.js#L65-L80](https://github.com/electron/asar/blob/3f243e2984b46991d9a535673c2c1ab41c95835d/lib/filesystem.js#L65-L80)
``` js
const transformed = options.transform && options.transform(p)
if (transformed) {
const tmpdir = await fs.mkdtemp(path.join(os.tmpdir(), 'asar-'))
const tmpfile = path.join(tmpdir, path.basename(p))
const out = fs.createWriteStream(tmpfile)
const readStream = fs.createReadStream(p)
await pipeline(readStream, transformed, out)
file.transformed = {
path: tmpfile,
stat: await fs.lstat(tmpfile)
}
size = file.transformed.stat.size
} else {
size = file.stat.size
}
```
> fix: CreateOptions.transform should return stream

- .circleci/config.yml
After making a trivial PR (#236), I realized that the CircleCI job for Linux was consistently failing.
I made a few upgrades and fixes:
* Run `sudo apt-get update` before `sudo apt-get install`.
* Migrate from deprecated `circleci/node:XX` images to the newer `cimg/node:XX.YY.ZZ` images. Needed to also install` xvfb` here because I think the newer images don't come with it installed.
* Move tests from Node 10/12 to 14/16 (current maintenance/LTS versions).
> build: update docker images

- lib/filesystem.js
Small tweak to improve the "file links out of the package" error message.
Inspired by https://github.com/electron/electron-rebuild/issues/1024. Giving more information in this error message could make it easier to understand what the problem is and how to solve it.
> feat: give better hints when failing due to bad links

- README.md
For clarification, `chromium-pickle-js` is the package used by this project (and under the Electron org), `chromium-pickle` is the original from the Atom org.
> docs: update links in README

- bin/asar.js
Looks like this without PR / before:
And with PR, performs as expected:
> fix: bad output on unknown CLI command

- lib/index.d.ts
- package.json
- yarn.lock
Inline types for old glob version, as discussed in https://github.com/electron/asar/pull/267
> fix: inline @types/glob, remove from deps

- README.md
- lib/disk.js
- lib/pickle.js
- package.json
- test/pickle-spec.js
- yarn.lock
[`electron/node-chromium-pickle-js`](https://github.com/electron/node-chromium-pickle-js) hasn't had a commit in nearly 7 years, and CI is non-operational there (see https://github.com/electron/node-chromium-pickle-js/pull/5).
Let's pull the code from there into this repo so that we can archive that repo.
This is a straight copy with minimal changes:
* `var` to `const`
* `new Buffer` to `Buffer.alloc` to make the linter happy
> chore: vendor chromium-pickle-js

- bin/asar.js
Minor cleanup: `asar.createPackageWithOptions` doesn't take a fourth argument, so it's safe to remove it
> fix: properly handle rejections on `createPackageWithOptions`

- lib/asar.js
When asar is extracting all files in an archive, it gives up when it encounters an error extracting one of them. This means that there are some files that can be extracted, but aren't. This change adds a try/catch block around file extraction so that the rest of the files are extracted if there is an issue with only one or a subset of the files in the archive.
> Don't give up when unable to extract some files

- lib/filesystem.js
It's amazing that I'm the first one to hit this bug - but if you have a folder structure where `asar` just happens to visit the directory _after_ it's added files, it will overwrite the existing files. That's bad, so this is fixing that.
> fix: Don't overwrite existing folders

- lib/filesystem.js
- test/cli-spec.js
> fix: better error message when extracting a file that doesn't exist in the archive

- src/asar.ts
- test/api-spec.js
- tsconfig.json
Fixes #323 
Older versions of `@electron/asar` exported all its functions at the top-level. TypeScript would take our old module, and if someone (like `@electron/forge`) ran `import asar from "@electron/asar"`, execute the following code:
```js
var asar = __importDefault(require("@electron/asar"))
var __importDefault = (this && this.__importDefault) || function (mod) {
return (mod && mod.__esModule) ? mod : { "default": mod };
};
// later, in our @electron/forge code:
await asar_1.default.createPackageWithOptions(...)
```
In our old version, that would result in:
```
asar = {
default: {
[... all our methods]
}
}
```
Now, we're setting `__esModule: true`, so TypeScript will just return:
```
asar = {
default: undefined 
}
```
And therefore, all code that looks like 
```js
await …
```
> fix: Export a "default" property

- src/crawlfs.ts
Just some tidying up to replace `<const>` syntax with `as const`. No functional impact.
> chore: prefer 'as const' syntax

- package.json
- src/types/glob.d.ts
- tsconfig.json
- yarn.lock
Basically just copy-pasted from #268; as discussed in https://github.com/electron/asar/pull/332#issuecomment-2435407933, we used to inline these types to avoid issues downstream, but that was lost when #320 landed so this is just restoring our previous workaround.
> fix: inline `@types/glob`

- src/asar.ts
- src/crawlfs.ts
- src/types/ambient.d.ts
- src/types/glob.ts
Follow-up to #336, as pointed out in https://github.com/electron/asar/pull/336#issuecomment-2444739563 I forgot to actually replace the usages of the `IOptions` type from `glob` by our local copy.
Fixes #330.
> fix: use local `glob` types

- .github/workflows/release.yml
Follow-up to #342, a copy and paste error led to using an outdated version here which doesn't work.
> ci: bump continuousauth/action version

- .github/workflows/test.yml
- package.json
- yarn.lock
This clears the audit. The latest version of `electron-mocha` requires Node.js >= 16 so this also drops Node.js 14 from our CI matrix - we'll be doing the Node.js minimum bump soon enough.
> build(dev-deps): bump electron-mocha and mocha to clear audit

- README.md
`grunt-asar` is now archived and hasn't received a commit in over a decade.
> docs: remove `grunt-asar` mention

- src/asar.ts
- test/cli-spec.js
- test/util/createSymlinkApp.js
Part 1 for fixing https://github.com/electron/universal/issues/117
This implementation achieves proposal `2b`
Excerpt below:
>Bypass minimatch with more explicit control over packaging options, similar as to asar ordering logic.
b. Leverage `options.ordering` configuration of electron/asar to pass in stringified JSON config for each file to be unpacked
In allowing more explicit control within the ordering file, advanced usage of electron/asar is provided (and kind of needed for electron/universal's current auto-unpack logic) to bypass limitations of the `minimatch` package
------
Right now, the "ordering" file is simply of format:
```
<file path>:<anything>
```
Right now, `electron/asar` only pulls the filename value before the `:` …
> feat: allow providing properties (such as `unpack`) in `ordering` input file

- src/asar.ts
- test/cli-spec.js
- test/util/createSymlinkApp.js
Reverts electron/asar#350
This is a breaking change that broke builds against the legacy `asar-ordering.txt` format.
> fix: revert "feat: allow providing properties (such as `unpack`) in `ordering` input file"

- .github/workflows/test.yml
- .mocharc.js
- mocha.setup.js
- package.json
- src/asar.ts
- test/__snapshots__/cli-spec.js.snap
- test/api-spec.js
- test/cli-spec.js
- test/filesystem-spec.js
- test/util/compareDirectories.js
- test/util/constants.js
- test/util/createSymlinkApp.js
- test/util/verifySmartUnpack.js
- test/util/walk.js
- yarn.lock
(Proposing this as an alternative to migrating to jest?)
Note: This was test-only changes, but I was encouraged to add jsdoc to `ordering`, so I'm not sure if `test:` is the correct tag now.
Following up from a convo and the jest PR, this provides interim support for snapshot tests while still leveraging `mocha` and `electron-mocha`. This PR adds dynamically generated `ordering.txt` files for test coverage of current ordering logic
Adds 3 unit tests to cover ordering.txt files w/:
- format: `filepath`
- format: `: filepath`
- format: `random-number : filepath`
Functionally, this PR adds:
- GHA `test.yaml` -> `fail-fast: false` allows the matrix jobs to continue even when one fails. This will allow verifying asar behavior across each node version before the overall test is marked as a …
> test: add `--ordering` unit tests with `chai`

- bin/asar.js
The message shown when calling `asar --help` wrongly showed an asterisk as a command.
> chore: fix asterisk in help message

- .github/workflows/test.yml
Testing this out, for some reason the Node.js 20.10 and Ubuntu 22.04 job has been stalled indefinitely at the install step.
> ci: bump Node.js 20 version to 20.19
