.travis.yml, lib/disk.js, package.json
This PR switches to use pure JavaScript implementation of chromium-pickle, closes #20.
=> Switch to chromium-pickle-js

lib/asar.js, lib/crawlfs.js, package.json, test/util/compareDirectories.js
Fixes https://github.com/atom/asar/issues/24
=> Use glob instead of walkdir

src/filesystem.coffee
=> good fix for Issue [#33](https://github.com/atom/asar/issues/33)

bin/asar, src/asar.coffee
Overview here: https://github.com/atom/atom/issues/10163
=> Add support for a hint file to optimize archive ordering

package.json
Fixes warnings logged about `graceful-fs` deprecations.
/cc @zeke
=> Upgrade mksnapshot

src/asar.coffee, src/filesystem.coffee
=> Fixes recursion range error

.gitattributes, .travis.yml, README.md, appveyor.yml, package.json
Adds an initial `appveyor.yml` to build on Windows.
=> Add Windows CI via AppVeyor

package.json, src/asar.coffee, test/api-spec.coffee, test/cli-spec.coffee
This is a continuation of https://github.com/electron/asar/pull/63 with added specs.
/cc @MarshallOfSound
=> Fix issue with unpack-dir glob matching

lib/filesystem.js
=> Do not return before write stream fully closes

.travis.yml, appveyor.yml
To make sure that the minimum Node version works on all platforms.
=> Test all Node LTS versions on Travis & AppVeyor

CHANGELOG.md
This was missed the last two releases.
=> Update CHANGELOG with 0.13.1 and 0.14.0

README.md
I had to look into the tests and changelog to figure this one out.
=> Update README for public API move to promises.

.travis.yml
For some reason we were missing a test platform.
=> chore: only use Travis CI for macOS testing

.releaserc.json, package-lock.json, package.json
Now with less spelling mistakes :grin:
=> chore: use the correct version of the CFA module

.releaserc.json, package-lock.json, package.json
=> chore: have semantic-release update the CHANGELOG file

lib/asar.js, lib/filesystem.js
This should primarily increase readability.
=> refactor: reduce the usage of anonymous functions

lib/index.d.ts, package-lock.json, package.json, test/index.test-d.ts
I made this mostly because I wanted to use it in Electron Packager's TypeScript definition, but it has the added bonus of partially documenting the API.
=> feat: add TypeScript definition

.circleci/config.yml
Signed-off-by: Rituka Patwal <ritukapatwal21@gmail.com>
=> chore: update the xcode version in circleci config

bin/asar.js
This reverts commit db163be081980bb1221a1633a9691b5d8e23426a.
That commit was accidentally pushed to `main` directly, this reverts it.
=> Revert "chore: modernize JS in bin/asar.js"

.circleci/config.yml, .releaserc.json, package.json, yarn.lock
As in title, no user facing changes
=> build: update deps to clean up yarn audit

.circleci/config.yml
Couldn't let @erickzhao have all the fun.
=> build: use cfa orb

src/asar.ts
`FileRecord` is used by Packager.
=> fix: export `FileRecord` and `DirectoryRecord` types
